services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "${NGINX_HTTP_PORT:-8080}:80"
    environment:
      FRONTEND_INTERNAL_PORT: ${FRONTEND_INTERNAL_PORT:-3000}
      BFF_INTERNAL_PORT: ${BFF_INTERNAL_PORT:-3000}
      GAME_INTERNAL_PORT: ${GAME_INTERNAL_PORT:-3001}
    volumes:
      - ../infra/nginx/nginx.dev.conf.template:/etc/nginx/templates/default.conf.template:ro
      - nginx_maps:/usr/share/nginx/html/maps
    depends_on:
      - frontend
      - bff
      - game_service
    networks: [backend]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  # game_service:
  #   profiles: ["dev"]
  #   build:
  #     context: ../backend/game
  #     dockerfile: Dockerfile
  #   container_name: game_service
  #   ports:
  #     - "${GAME_PORT:-3001}:3001"
  #     - "${GAME_DEBUG_PORT:-9231}:9231"
  #   volumes:
  #     - nginx_maps:/app/generated/maps
  #   networks: [backend]







volumes:
  nginx_maps: