
// get all user from BFF
k POST http://localhost:3000/auth/register \
  -H "Content-Type: application/json" \
  -d '{"email":"test+1@example.com","password":"P@ssw0rd","displayName":"Test User"}' | jq .

POST http://localhost:3004/internal/stats/user
Content-Type: application/json

{
  "userId": "{{userId}}",
  "xp": 50,
  "level": 2,
  "wins": 1,
  "losses": 0,
  "kills": 10,
  "deaths": 2
}
