export enum AuditActionDto {
  REGISTER = 'REGISTER',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  GOOGLE_EXCHANGE = 'GOOGLE_EXCHANGE',
  USER_DISABLED = 'USER_DISABLED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  SESSIONS_REVOKED = 'SESSIONS_REVOKED',
}
